-- MySQL Script generated by MySQL Workbench
-- Fri Mar 22 03:15:26 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `Pizzeria` ;

-- -----------------------------------------------------
-- Table `Pizzeria`.`Pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Pizza` (
  `idPizza` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(15) NOT NULL,
  `url_imagen` VARCHAR(20) NOT NULL,
  `precio_chica` DECIMAL NOT NULL,
  `precio_mediana` DECIMAL NOT NULL,
  `Precio_grande` DECIMAL NOT NULL,
  `precio_familiar` DECIMAL NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idPizza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Paquete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Paquete` (
  `idPaquete` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(15) NOT NULL,
  `url_imagen` VARCHAR(20) NOT NULL,
  `precio` DECIMAL NOT NULL,
  `Descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idPaquete`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Orden` (
  `idOrden` INT NOT NULL,
  `Precio_total` DECIMAL NOT NULL,
  `DATE` DATE NULL,
  PRIMARY KEY (`idOrden`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `idPizza` INT NULL,
  `idPaquete` INT NULL,
  `idOrden` INT NULL,
  `tam_pizza` INT NULL,
  `cantidad` INT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `idPizza_idx` (`idPizza` ASC),
  INDEX `idOrden_idx` (`idOrden` ASC),
  INDEX `idPaquete_idx` (`idPaquete` ASC),
  CONSTRAINT `idPizza`
    FOREIGN KEY (`idPizza`)
    REFERENCES `Pizzeria`.`Pizza` (`idPizza`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idOrden`
    FOREIGN KEY (`idOrden`)
    REFERENCES `Pizzeria`.`Orden` (`idOrden`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idPaquete`
    FOREIGN KEY (`idPaquete`)
    REFERENCES `Pizzeria`.`Paquete` (`idPaquete`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
